Script started on Sun Oct 14 20:37:38 2012
bash-3.2$ exit./TestExec g++ TestCases.cpp -o TestExec
bash-3.2$ g++ TestCases.cpp -o TestExecbash-3.2$ exit[K./TestExec 
This is the driver that will test every case in the Test Cases document.
TEST: Adding a Polynomial to a Polynomial with 0 terms.
How many terms in this polynomial? 3

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 5
Enter the degree for the term (Degree >= 0): 3

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: 2
Enter the degree for the term (Degree >= 0): 2

Enter the data for term 3 of the polynomial.
Enter the coefficient for the term: 1
Enter the degree for the term (Degree >= 0): 1
Term count is: 3
How many terms in this polynomial? 0
Term count is: 0
Expected Result: 5x3 + 2x2 + x
Actual Result: 5x^3 + 2x^2 + 1x^1

TEST: Adding two Polynomials.
Polynomial 1
How many terms in this polynomial? 3

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 8
Enter the degree for the term (Degree >= 0): 4

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: 9
Enter the degree for the term (Degree >= 0): 3

Enter the data for term 3 of the polynomial.
Enter the coefficient for the term: 6
Enter the degree for the term (Degree >= 0): 1
Term count is: 3
Polynomial 2
How many terms in this polynomial? 3

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 8
Enter the degree for the term (Degree >= 0): 5

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: 6
Enter the degree for the term (Degree >= 0): 3

Enter the data for term 3 of the polynomial.
Enter the coefficient for the term: 2
Enter the degree for the term (Degree >= 0): 2
Term count is: 3
Polynomial 1: 8x^4 + 9x^3 + 6x^1

Polynomial 2: 8x^5 + 6x^3 + 2x^2

Expected Result: 5x5 + 8x4 + 15x3 + 2x2 + 6x
Actual Result: 8x^5 + 8x^4 + 15x^3 + 2x^2 + 6x^1

TEST: Adding a Polynomial to an integer, 5.
How many terms in this polynomial? 4

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: -6
Enter the degree for the term (Degree >= 0): 8

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: 4
Enter the degree for the term (Degree >= 0): 5

Enter the data for term 3 of the polynomial.
Enter the coefficient for the term: -2
Enter the degree for the term (Degree >= 0): 1

Enter the data for term 4 of the polynomial.
Enter the coefficient for the term: 3
Enter the degree for the term (Degree >= 0): 0
Term count is: 4
Polynomial 1: -6x^8 + 4x^5 -2x^1 + 3

Expected Result: -6x8 + 4x5 -2x + 8
Actual Result: -6x^8 + 4x^5 -2x^1  + 8
TEST: Adding an integer, 5, to a Polynomial
How many terms in this polynomial? 4

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: -6
Enter the degree for the term (Degree >= 0): 8

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: 4
Enter the degree for the term (Degree >= 0): 5

Enter the data for term 3 of the polynomial.
Enter the coefficient for the term: -2
Enter the degree for the term (Degree >= 0): 1

Enter the data for term 4 of the polynomial.
Enter the coefficient for the term: 3
Enter the degree for the term (Degree >= 0): 0
Term count is: 4
Polynomial 1: -6x^8 + 4x^5 -2x^1 + 3

Expected Result: -6x8 + 4x5 -2x + 8
Actual Result: -6x^8 + 4x^5 -2x^1  + 8

TEST: Setting 2 Polynomials equal to each other.
How many terms in this polynomial? 6

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 9
Enter the degree for the term (Degree >= 0): 7

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: 8
Enter the degree for the term (Degree >= 0): 4

Enter the data for term 3 of the polynomial.
Enter the coefficient for the term: 2
Enter the degree for the term (Degree >= 0): 3

Enter the data for term 4 of the polynomial.
Enter the coefficient for the term: 4
Enter the degree for the term (Degree >= 0): 2

Enter the data for term 5 of the polynomial.
Enter the coefficient for the term: 6
Enter the degree for the term (Degree >= 0): 1

Enter the data for term 6 of the polynomial.
Enter the coefficient for the term: 2
Enter the degree for the term (Degree >= 0): 0
Term count is: 6
How many terms in this polynomial? 1

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 4
Enter the degree for the term (Degree >= 0): 9
Term count is: 1
Polynomial 1: 9x^7 + 8x^4 + 2x^3 + 4x^2 + 6x^1 + 2

Polynomial 2: 4x^9

SETTING POLYNOMIALS EQUAL TO EACH OTHER...
Results: 
Polynomial 1: 4x^9

Polynomial 2: 4x^9

TEST: Multiplying 2 Polynomials.
How many terms in this polynomial? 2

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 1
Enter the degree for the term (Degree >= 0): 3

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: -3
Enter the degree for the term (Degree >= 0): 4
Term count is: 2
How many terms in this polynomial? 2

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 1
Enter the degree for the term (Degree >= 0): 2

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: -2
Enter the degree for the term (Degree >= 0): 1
Term count is: 2
Polynomial 1: -3x^4 + 1x^3

Polynomial 2: 1x^2 -2x^1

Expected Result: - 3x6 + 7x5 - 2x4
Actual Result: -3x^6 + 7x^5 -2x^4 

TEST: Multiplying an integer, 4, by Polynomial 1
How many terms in this polynomial? 4

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 7
Enter the degree for the term (Degree >= 0): 3

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: -2
Enter the degree for the term (Degree >= 0): 2

Enter the data for term 3 of the polynomial.
Enter the coefficient for the term: 8
Enter the degree for the term (Degree >= 0): 1

Enter the data for term 4 of the polynomial.
Enter the coefficient for the term: 5
Enter the degree for the term (Degree >= 0): 0
Term count is: 4
Expected Result: 28x3 - 8x2 + 32x + 20
Actual Result: 28x^3 -8x^2 + 32x^1 + 20

TEST: Multiplying Polynomial 1 by an integer, 4.
Expected Result: 28x3 - 8x2 + 32x + 20
Actual Result: 28x^3 -8x^2 + 32x^1 + 20

TEST: Overwriting an existing Polynomial by reading from a file.
How many terms in this polynomial? 2

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 3
Enter the degree for the term (Degree >= 0): 4

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: 1
Enter the degree for the term (Degree >= 0): 2
Term count is: 2
Polynomial 1: 3x^4 + 1x^2

What is the name of the file? textPoly2.txt
The overwritten Polynomial is: 3x^9 + 4x^3 + 1x^2 + 2x^1 
TEST: Display Polynomial 1 in descending order.
How many terms in this polynomial? 7

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 3
Enter the degree for the term (Degree >= 0): 2

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: 5
Enter the degree for the term (Degree >= 0): 7

Enter the data for term 3 of the polynomial.
Enter the coefficient for the term: 9
Enter the degree for the term (Degree >= 0): 3

Enter the data for term 4 of the polynomial.
Enter the coefficient for the term: 10
Enter the degree for the term (Degree >= 0): 1

Enter the data for term 5 of the polynomial.
Enter the coefficient for the term: -8
Enter the degree for the term (Degree >= 0): 8

Enter the data for term 6 of the polynomial.
Enter the coefficient for the term: 20
Enter the degree for the term (Degree >= 0): 4

Enter the data for term 7 of the polynomial.
Enter the coefficient for the term: -1
Enter the degree for the term (Degree >= 0): 5
Term count is: 7
After sorting, Polynomial 1: -8x^8 + 5x^7 -1x^5 + 20x^4 + 9x^3 + 3x^2 + 10x^1

TEST: Evaulate Polynomial 1 for an integer, 3.
How many terms in this polynomial? 7

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: -8
Enter the degree for the term (Degree >= 0): 8

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: 5
Enter the degree for the term (Degree >= 0): 7

Enter the data for term 3 of the polynomial.
Enter the coefficient for the term: -1
Enter the degree for the term (Degree >= 0): 5

Enter the data for term 4 of the polynomial.
Enter the coefficient for the term: 20
Enter the degree for the term (Degree >= 0): 4

Enter the data for term 5 of the polynomial.
Enter the coefficient for the term: 9
Enter the degree for the term (Degree >= 0): 3

Enter the data for term 6 of the polynomial.
Enter the coefficient for the term: 3
Enter the degree for the term (Degree >= 0): 2

Enter the data for term 7 of the polynomial.
Enter the coefficient for the term: 10
Enter the degree for the term (Degree >= 0): 1
Term count is: 7
Expected Result: -39876
Actual Result: -39876
TEST: Simplify and order a Polynomial with multiple terms of equal degree.
How many terms in this polynomial? 5

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 5
Enter the degree for the term (Degree >= 0): 3

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: 45
Enter the degree for the term (Degree >= 0): 3

Enter the data for term 3 of the polynomial.
Enter the coefficient for the term: 10
Enter the degree for the term (Degree >= 0): 4

Enter the data for term 4 of the polynomial.
Enter the coefficient for the term: 2
Enter the degree for the term (Degree >= 0): 4

Enter the data for term 5 of the polynomial.
Enter the coefficient for the term: 1
Enter the degree for the term (Degree >= 0): 1
Term count is: 5
Expected Result: 12x4 + 50x3 + x
After simplifying and sorting, Polynomial: 12x^4 + 50x^3 + 1x^1  

TEST: Set a Polynomial equal to an integer, 12.
How many terms in this polynomial? 2

Enter the data for term 1 of the polynomial.
Enter the coefficient for the term: 8
Enter the degree for the term (Degree >= 0): 5

Enter the data for term 2 of the polynomial.
Enter the coefficient for the term: -2
Enter the degree for the term (Degree >= 0): 3
Term count is: 2
Polynomial 1: 8x^5 -2x^3

After setting Polynomial 1 equal to 12, the result is: 12




The tests have concluded.
Thank you for using this program.
bash-3.2$ exit
exit

Script done on Sun Oct 14 20:42:34 2012
